"""Vietnamese sentences for robot-voice negative generation.

These mimic the kinds of things the robot actually says (weather, time,
confirmations, small talk, numbers, questions) so the model learns to reject the
robot's own voice across varied phonetic content. NONE contains the wake phrase
"Mai ơi" or anything phonetically close to it.
"""

ROBOT_NEGATIVE_SENTENCES = [
    "Hôm nay trời nắng đẹp, nhiệt độ khoảng ba mươi độ.",
    "Bây giờ là chín giờ tối rồi đó nha.",
    "Tao bật đèn phòng khách cho mày nè.",
    "Đã tắt quạt phòng ngủ rồi nha.",
    "Trời chiều nay có mưa nhẹ, nhớ mang áo mưa.",
    "Mày muốn nghe bài nhạc nào để tao mở cho.",
    "Ừ để tao kiểm tra thời tiết ngày mai giúp mày.",
    "Nhiệt độ ngoài trời đang là hai mươi bảy độ.",
    "Tao vừa tắt hết đèn nhà trên rồi đó.",
    "Muốn nghe tin tức buổi sáng không để tao đọc cho.",
    "Cái này thì tao chưa biết, để tao tìm thử nha.",
    "Giờ này ngoài đường chắc kẹt xe dữ lắm.",
    "Chúc mày ngủ ngon, mai gặp lại nha.",
    "Ăn cơm chưa vậy, đói bụng thì nói tao.",
    "Tao đang mở nhạc bolero cho mày nghe nè.",
    "Đèn nhà bếp đã được bật lên rồi.",
    "Ngày mai trời se lạnh, nhớ mặc ấm vào.",
    "Bây giờ đã là mười hai giờ trưa.",
    "Để tao chuyển qua bài hát tiếp theo nha.",
    "Máy lạnh phòng đã chỉnh xuống hai mươi sáu độ.",
    "Có chuyện gì vui kể tao nghe với.",
    "Tao không hiểu lắm, mày nói lại được không.",
    "Sáng nay có sương mù, chạy xe cẩn thận nha.",
    "Nhà mình hôm nay có khách tới chơi hả.",
    "Tao đã dừng nhạc lại rồi đó.",
    "Trời tối rồi, để tao bật đèn ngoài sân cho.",
    "Cuối tuần này mày có đi đâu chơi không.",
    "Nhiệt độ trong nhà đang khá dễ chịu.",
    "Tao vừa mở tivi phòng khách lên rồi.",
    "Mày cần tao nhắc gì thì cứ nói nha.",
    "Bữa nay ăn gì để tao gợi ý cho.",
    "Loa phòng ngủ đang phát nhạc nhẹ.",
    "Mai là chủ nhật rồi, nghỉ ngơi cho khỏe.",
    "Tao đã giảm âm lượng xuống một chút.",
    "Ngoài trời đang mưa to lắm đó nha.",
    "Đừng lo, để tao xử lý chuyện đó cho.",
    "Giờ ăn tối rồi, cả nhà vào bàn thôi.",
    "Con mèo nhà mình lại trốn đâu mất tiêu.",
    "Tao thấy trời hôm nay đẹp ghê luôn.",
    "Chờ tao chút xíu, tao đang tìm thông tin.",
    "Đèn ngủ đã được tắt cho mày rồi.",
    "Nhớ uống đủ nước trong ngày nha.",
    "Tao chúc mày một ngày làm việc vui vẻ.",
    "Cà phê sáng nay uống ngon không vậy.",
    "Trời đang chuyển gió, chắc sắp mưa rồi.",
    "Tao đã mở playlist nhạc trẻ cho mày.",
    "Phòng khách hơi nóng, để tao bật quạt nha.",
    "Chút nữa nhớ khóa cửa trước khi ngủ.",
    "Hôm nay là thứ tư, ngày mười bốn tháng bảy.",
    "Tao vừa tăng tốc độ quạt lên một nấc.",
    "Mày muốn tao kể chuyện cười cho nghe không.",
    "Nước ngoài trời giờ chắc mát lắm đây.",
    "Tao đã bật hết đèn phòng khách rồi nha.",
    "Đừng thức khuya quá, hại sức khỏe lắm đó.",
    "Sáng mai mấy giờ mày cần tao gọi dậy.",
    "Tao đang phát bản tin thời tiết cho mày nghe.",
    "Nhà bên cạnh chắc đang nấu gì thơm ghê.",
    "Được rồi, tao tắt nhạc ngay cho mày.",
    "Chúc cả nhà buổi tối ấm áp, vui vẻ nha.",
    "Trời hôm nay âm u, chắc chiều có giông.",
]
